name: Appium CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: Install the Emulator
      run: |
        chmod +x ./scripts/RunAppiumServer.sh
        ./scripts/RunAppiumServer.sh
      shell: bash   
    - name: run appium ios tests
      run: mvn clean test -Pios
